/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;
import com.opencsv.*;
import javafx.application.Application;
import javafx.scene.Scene;  
import javafx.scene.control.Button;  
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import java.io.FileReader;
import java.util.ArrayList;


public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {
        ArrayList<Order> orders = readCSVData("data/SuperStoreOrders.csv");

        ///////////////////////////////////////////////////////////mess around with other layouts
        HBox root = new HBox();

        Button salesBtn = new Button("Average Sales");
        salesBtn.setOnAction(e -> {
            long totalSales = orders.stream().mapToLong(Order::sales).sum();
            double averageSales = (double) totalSales / orders.size();
            System.out.println("Total Average Sales: " + averageSales);
        });

        ////////////////////////////////////////////////////////////Change to a search/select
        Button customerPerStateBtn = new Button("Customers in Kentucky");
        customerPerStateBtn.setOnAction(e -> {
            int kentuckyCount = (int) orders.stream()
                    .map(Order::location)
                    .filter(location -> "Kentucky".equals(location.state()))
                    .count();
            System.out.println("Customers in Kentucky: " + kentuckyCount);
        });

        root.getChildren().addAll(salesBtn, customerPerStateBtn);
        Scene scene = new Scene(root, 300, 300);
        primaryStage.setScene(scene);
        primaryStage.setTitle("SuperStore Data");
        primaryStage.setOnCloseRequest(event -> System.exit(0));
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch(args);
        //System.out.println(new App().getGreeting());
        //List<Order> orders = readCSVData("data/SuperStoreOrders.csv");
    }
    private static ArrayList<Order> readCSVData(String file) {
        ArrayList<Order> allOrders = new ArrayList<>();
        try (CSVReader csvReader = new CSVReaderBuilder(new FileReader(file))
                .withSkipLines(1)
                .withCSVParser(new CSVParserBuilder().withSeparator(';').build())
                .build()) {
            csvReader.iterator().forEachRemaining(order -> {
                try {
                                                    //customerId, Name, Segment
                    Customer customer = new Customer(order[5], order[6], order[7]);
                    String orderDate = order[2];
                    String shippingMode = order[4];
                                                    //City,     State,      Region
                    Location location = new Location(order[9], order[10], order[12]);
                                                //productId, category, sub-cat,      name
                    Product product = new Product(order[13], order[14], order[15], order[16]);
                    //Commas were randomly interpolated in the data that weren't shown in Excel,
                    //so replace with blanks
                    int sales = replaceCommaAndParse(order[17]);
                    int quantity = replaceCommaAndParse(order[18]);
                    int discount = replaceCommaAndParse(order[19]);
                    int profit = replaceCommaAndParse(order[20]);
                    Order fullOrder = new Order(customer, orderDate, shippingMode, location,
                            product, sales, quantity, discount, profit);
                    allOrders.add(fullOrder);
                } catch (NumberFormatException e) {
                    System.err.println("Failed to parse data in Row ID: " + order[0]);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
        return allOrders;
    }
    private static int replaceCommaAndParse(String orderItem){
        try{
            return Integer.parseInt(orderItem.replace(",",""));
        }catch (NumberFormatException e){
            System.err.println("Failed to parse string: " + orderItem);
            return 0; ///////////////////////////////////////////////////////////////////////////Change to Optional?
        }
    }
    public String getGreeting() {
        return "Hello World!";
    }
}  