name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: App test
      id: app-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: App test
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        APP-TEST_RESULTS: "${{steps.app-test.outputs.result}}"
      with:
        runners: app-test
